import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { formatDate, getBlogPosts } from './utils'

describe('getBlogPosts', () => {
  // Reads the real app/old-site/blog/posts directory rather than a fixture —
  // these are the actual posts the site ships, so parsing them correctly is
  // exactly what matters. Regenerated by the filesystem, not hardcoded, so a
  // renamed/added/removed post can't silently drift out of sync with this
  // test's expectations for the fields every post below asserts on.
  const posts = getBlogPosts()

  it('finds every known project post by slug', () => {
    const slugs = posts.map((p) => p.slug)
    expect(slugs).toEqual(
      expect.arrayContaining([
        'wonderbot-1000',
        'playswapmeat',
        'house-ops',
        'moonbob-money',
        'laango-django',
        'apre-method',
      ])
    )
  })

  it('parses frontmatter into title/publishedAt/summary, and strips it from content', () => {
    const post = posts.find((p) => p.slug === 'apre-method')
    expect(post).toBeDefined()
    expect(post!.metadata.title).toBe('The APRE Method')
    expect(post!.metadata.publishedAt).toBe('2025-10-20')
    expect(post!.metadata.summary).toContain('APRE protocols')
    // The --- frontmatter fences themselves must not leak into content.
    expect(post!.content).not.toContain('---')
    expect(post!.content).not.toContain('title:')
  })

  it('derives the slug from the filename, not from frontmatter', () => {
    const post = posts.find((p) => p.slug === 'house-ops')
    expect(post).toBeDefined()
    // house-ops.mdx's own title is "Household OS" — a different string from
    // its filename/slug — so this also guards against slug and title ever
    // being conflated.
    expect(post!.metadata.title).toBe('Household OS')
  })
})

describe('formatDate', () => {
  beforeEach(() => {
    // "Today" is baked into the relative-date math (yearsAgo/monthsAgo/
    // daysAgo all diff against `new Date()`), so it has to be pinned for the
    // relative cases to be deterministic.
    vi.useFakeTimers()
    vi.setSystemTime(new Date('2026-06-15T12:00:00'))
  })

  afterEach(() => {
    vi.useRealTimers()
  })

  it('formats an absolute date without the relative suffix by default', () => {
    expect(formatDate('2026-05-27')).toBe('May 27, 2026')
  })

  it('reports days-ago for a date earlier this month', () => {
    expect(formatDate('2026-06-10', true)).toBe('June 10, 2026 (5d ago)')
  })

  it('reports months-ago for a date earlier this year', () => {
    expect(formatDate('2026-03-15', true)).toBe('March 15, 2026 (3mo ago)')
  })

  it('reports years-ago for a date in a prior year', () => {
    expect(formatDate('2025-06-15', true)).toBe('June 15, 2025 (1y ago)')
  })

  it('reports "Today" for the current date', () => {
    expect(formatDate('2026-06-15', true)).toBe('June 15, 2026 (Today)')
  })
})
